name: Update Issue Template

on:
  workflow_run:
    workflows:
      - Publish Plugins
    types:
      - completed

jobs:
  update_template:
    #if: github.repository == 'LNReader/lnreader-plugins' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Recreating report issue template
        run: |
          node ./.github/scripts/createOptions.cjs

      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: '[skip ci] Update issue template with plugin dropdown options'
          branch: 'update-issue-template'
          title: 'Update Issue Template'
          body: |
            This PR updates the issue template with the latest plugin dropdown options.
            If this PR already exists, it will be updated automatically with the latest changes.
          labels: 'bot'
          base: 'master'
          delete-branch: true
